import Head from "next/head";
import Home_Page from "../components/home";
export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-1.jpg" />
      </Head>
      <Home_Page  />
    </>
  );
}
