import Head from "next/head";
import Register_Page from "../components/register";
const Register = () => {
  return (
    <>
      <Head>
        <title>Register Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-3.png" />
      </Head>
      <Register_Page />
    </>
  );
};

export default Register;
