import Head from "next/head";
import axios from "axios";
import { useState, useContext } from "react";
import New_Category from "../../../components/Admin/categorys/create";
import AuthContext from "../../../context/auth";
const Create = () => {
  // accessToken
  const context = useContext(AuthContext);
  const accessToken = context.isUser.accessToken;
  // set up message
  const [message, setMessage] = useState();
  // create
  const create = async (item) => {
    try {
      const category = await axios.post(
        "http://localhost:3000/api/categorys",
        item,
        { headers: { token: `User ${accessToken}` } }
      );
      const categoryData = await category.data;
      setMessage(categoryData);
    } catch (error) {
      // console.log(error);
      const dataLogin = error.response.data;
      setMessage(dataLogin);
    }
  };
  return (
    <>
      <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-3.png" />
      </Head>
      <New_Category createData={create} messageData={message} />
    </>
  );
};

export default Create;
