import Head from "next/head";
import axios from "axios";
import { useState, useContext } from "react";
import Edit_Book from "../../../components/Admin/books/edit";
const Edit = ({ book }) => {
  const name = book.book.name;
  const bookId = book.book._id;
  const [bookName, setBookName] = useState(name);
  const [message, setMessage] = useState();
  const [data, setData] = useState(book);
  const updateData = async (item) => {
    try {
      const bookEdit = await axios.patch(
        `http://localhost:3000/api/books/${bookId}`,
        item
      );
      setBookName(bookEdit.data.book.name);
      setMessage(bookEdit.data);
      setData(bookEdit.data);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>Edit: {bookName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-4.png" />
      </Head>
      <Edit_Book
        Data={data}
        nameData={bookName}
        messageData={message}
        editData={updateData}
      />
    </>
  );
};

export default Edit;
export async function getStaticPaths() {
  const res = await fetch(`http://localhost:3000/api/books`);
  const data = await res.json();
  const book = data.books;
  const paths = book.map((item) => {
    return {
      params: { id: item._id },
    };
  });
  return {
    paths,
    fallback: false, // can also be true or 'blocking'
  };
}
export async function getStaticProps(context) {
  const item = context.params.id;
  const res = await fetch(`http://localhost:3000/api/books/${item}`);
  const book = await res.json();
  return {
    props: { book },
  };
}
