import Head from "next/head";
import axios from "axios";
import { useState, useContext } from "react";
import New_Book from "../../../components/Admin/books/create";
import AuthContext from "../../../context/auth";
const Create = ({ categorys }) => {
  const context = useContext(AuthContext);
  const accessToken = context.isUser.accessToken;
  // set up message
  const [message, setMessage] = useState();
  // create
  const create = async (item) => {
    try {
      const book = await axios.post("http://localhost:3000/api/books", item, {
        headers: { token: `User ${accessToken}` },
      });
      const bookData = await book.data;
      setMessage(bookData);
    } catch (error) {
      const dataBook = error.response.data;
      setMessage(dataBook);
    }
  };
  return (
    <>
      <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-3.png" />
      </Head>
      <New_Book
        categroyData={categorys}
        createData={create}
        messageData={message}
      />
    </>
  );
};

export default Create;
export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/categorys");
  const categorys = await res.json();
  return {
    props: {
      categorys,
    },
  };
};
