import Head from "next/head";
import axios from "axios";
import { useState, useEffect } from "react";
import List_Book from "../../../components/Admin/books/list";
const Book = ({ books }) => {
  const [getMessage, setMessage] = useState();
  const [getStatus, setStatus] = useState(true);
  const [getBooks, setBooks] = useState(books);
  //get data
  useEffect(() => {
    const getAllBooks = async () => {
      try {
        const getAllBooks = await axios.get("http://localhost:3000/api/books");
        setBooks(getAllBooks.data);
      } catch (error) {
        console.log(error);
      }
    };
    getAllBooks();
  }, [getStatus]);
  // delete
  const deleteItem = async (item) => {
    try {
      const itemId = await item._id;
      const deleteBook = await axios.delete(
        `http://localhost:3000/api/books/${itemId}`
      );
      setMessage(deleteBook.data);
      setStatus(!getStatus);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-1.jpg" />
      </Head>
      <List_Book
        bookData={getBooks}
        deteteData={deleteItem}
        messageData={getMessage}
      />
    </>
  );
};

export default Book;
export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/books");
  const books = await res.json();
  return {
    props: {
      books,
    },
  };
};
