import Head from "next/head";
import Github_Page from "../../components/Admin/github";
const Github = ({ githubs }) => {
  const github = githubs.githubs;
  return (
    <>
      <Head>
        <title>Github</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-4.png" />
      </Head>
      <Github_Page githubData={github} />
    </>
  );
};

export default Github;
export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/passport/githubs");
  const githubs = await res.json();
  return {
    props: {
      githubs,
    },
  };
};
