import Head from "next/head";
import Google_Page from "../../components/Admin/google";
const Google = ({ googles }) => {
  const google = googles.googles;
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-3.png" />
      </Head>
      <Google_Page googleData={google} />
    </>
  );
};

export default Google;
export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/passport/googles");
  const googles = await res.json();
  return {
    props: {
      googles,
    },
  };
};
