import Head from "next/head";
import Home_Page from "../components/Main/home";
const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-1.jpg" />
      </Head>
      <Home_Page />
    </>
  );
};

export default Home;
