import Head from "next/head";
import { useContext } from "react";
import { useRouter } from "next/router";
import AuthContext from "../context/auth";
import Login_Page from "../components/Main/login";
const Login = () => {
  const context = useContext(AuthContext);
  const router = useRouter();
  const login = async (item) => {
    await context.onLogin(item);
    await router.push("/");
  };
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-2.jpg" />
      </Head>
      <Login_Page loginData={login} />
    </>
  );
};

export default Login;
