import Head from "next/head";
import Register_Page from "../components/Main/register";
const Register = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-2.jpg" />
      </Head>
      <Register_Page />
    </>
  );
};

export default Register;
