import Head from "next/head";
import axios from "axios";
import { useState, useEffect } from "react";
import Room_Page from "../components/Main/room";
const Room = () => {
  const [rooms, setRooms] = useState([]);
  const [page, setPage] = useState(1);
  const [page_total, setPage_Total] = useState();
  const [total_item, setTotal_Item] = useState();
  useEffect(() => {
    const getAllRooms = async () => {
      try {
        const getAllRooms = await axios.get(
          `http://localhost:3000/api/rooms?page=${page}`
        );
        setRooms(getAllRooms.data.rooms);
        setPage(getAllRooms.data.page);
        setPage_Total(getAllRooms.data.page_total);
        setTotal_Item(getAllRooms.data.total_item);
      } catch (error) {
        console.log(error);
      }
    };
    getAllRooms();
  }, [page]);
  const newPage = async (item) => {
    setPage(item);
  };
  return (
    <>
      <Head>
        <title>Room</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-2.jpg" />
      </Head>
      <Room_Page
        roomData={rooms}
        Page={page}
        Page_Total={page_total}
        Total_Item={total_item}
        Click_Page={newPage}
      />
    </>
  );
};

export default Room;
