import Head from "next/head";
import Edit_User from "../../../components/Admin/users/edit";
const Detail = () => {
  return (
    <>
      <Head>
        <title>Edit User Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-1.jpg" />
      </Head>
      <Edit_User />
    </>
  );
};

export default Detail;
