import Head from "next/head";
import List_User from "../../components/users/list";
const User = () => {
  return (
    <>
      <Head>
        <title>User Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-1.jpg" />
      </Head>
      <List_User />
    </>
  );
};

export default User;
