import Head from "next/head";
import List_User from "../../../components/Admin/users/list";
const User = ({ users }) => {
  return (
    <>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-1.jpg" />
      </Head>
      <List_User userData={users} />
    </>
  );
};

export default User;
export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/users");
  const users = await res.json();
  return {
    props: {
      users,
    },
  };
};
